forge "https://forgeapi.puppetlabs.com"

# Puppet Forge
mod 'puppetlabs/apt', '4.5.0'
mod 'puppetlabs/concat', '4.1.1'
mod 'puppetlabs/inifile', '2.2.0'
mod 'puppetlabs/java', '2.4.0'
mod 'puppetlabs/ntp', '7.1.0'
mod 'puppetlabs/postgresql', '5.2.1'
mod 'puppetlabs/stdlib', '4.24.0'

# Stuff that our site profiles need
mod 'elastic/elasticsearch', '6.1.0'
mod 'herculesteam/augeasproviders_core', '2.1.4'
mod 'herculesteam/augeasproviders_ssh', '2.5.3'
mod 'saz/locales', '2.5.0'
