---
kitodo_publication_api : "http://mock.kitodo.presentation/api"
qucosa_purl_url : "http://mock.qucosa.resolver/id"

services:
  mets:
    war: qucosa-metsdisseminator-2.2.0.war
    url: https://github.com/qucosa/qucosa-fcrepo-metsdisseminator/releases/download/v2.2.0
    checksum: sha1:d891b69725154d3ecd0a9b245628b4e1071bd0f2
    params:
      "fedora.host.url": "{{ fedora_service_url }}"

  epicur:
    war: qucosa-epicurdisseminator-1.1.5.war
    url: https://github.com/qucosa/qucosa-fcrepo-epicurdisseminator/releases/download/v1.1.5
    checksum: sha1:ef03b636bbdcb919d31427f239217427e68cf2b3
    params:
      "transfer.url.pattern": "{{ kitodo_publication_api }}/##PID##/attachment/##DSID##/"
      "transfer.url.pidencode": "yes"
      "frontpage.url.pattern": "{{ qucosa_purl_url }}/##PID##"

  winibwppn:
    war: qucosa-fcrepo-winibwppn-1.1.0.war
    url: https://github.com/qucosa/qucosa-fcrepo-winibwppn/releases/download/v1.1.0
    checksum: sha1:e1a123056937fc7e1c58f61e08b39fe234ad8c3b
    params:
      "fedora.host.url": "{{ fedora_service_url }}"

  xmetadissplus:
    war: qucosa-fcrepo-xmetadissplus-1.3.0.war
    url: https://github.com/qucosa/qucosa-fcrepo-xmetadissplus/releases/download/v1.3.0
    checksum: sha1:94d4d7283c5607683757b9ab1db3ee875241a1a6

  dc:
    war: qucosa-fcrepo-dcdisseminator-1.1.7.war
    url: https://github.com/qucosa/qucosa-fcrepo-dcdisseminator/releases/download/v1.1.7
    checksum: sha1:c8f34f4fe64bc2c1e516ab150f297464998d1905

  zip:
    war: qucosa-fcrepo-zipdisseminator-1.0.2.war
    url: https://github.com/qucosa/qucosa-fcrepo-zipdisseminator/releases/download/v1.0.2
    checksum: sha1:7fc87c49e4192afa504c0599adf898f8c8c8e51e
